/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    'BaseButton.stories': typeof import('./src/components/BaseButton.stories.vue')['default']
    BaseInputText: typeof import('./src/components/BaseInputText.vue')['default']
    copy: typeof import('./src/components/BaseButton copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Task: typeof import('./src/components/Task.vue')['default']
  }
}
