/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseInputText: typeof import('./src/components/BaseInputText.vue')['default']
    Footer: typeof import('./src/layouts/footer/Footer.vue')['default']
    Foter: typeof import('./src/layouts/footer/Foter.vue')['default']
    Header: typeof import('./src/layouts/header/Header.vue')['default']
    Hooter: typeof import('./src/layouts/footer/Hooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Task: typeof import('./src/components/Task.vue')['default']
  }
}
